### ISSUE TITLE
False "Unconfirmed: Timed out" error

### ISSUE THREAD

**Issue by mvines** [solana-labs/break#139]
I breaked a little, devnet, and got some red boxes:
![image](https://user-images.githubusercontent.com/1281082/79889645-2e749b80-83b3-11ea-875a-9836f6fb3443.png)
, which showed
![image](https://user-images.githubusercontent.com/1281082/79889665-37fe0380-83b3-11ea-8bdb-ec836a6bd803.png)
but when I viewed in explorer the transaction was all good:
![image](https://user-images.githubusercontent.com/1281082/79889704-4ba96a00-83b3-11ea-8a25-41a5753e9f5d.png)

**Comment by jstarry** [comment]
Found one cause...

The RPC pubsub service doesn't always notify on account changes. Will write up an issue in github.com/solana-labs/solana after some more investigation

**Comment by jstarry** [comment]
This has since been fixed
