### ISSUE TITLE
Multiple open tabs in chrome seems to prevent the game from loading

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/break#187]
Multiple open tabs in chrome seems to prevent the game from loading.  They are probably spending the funds without fully loading the contract.

**Comment by jstarry** [comment]
Nice bug, didn't think about this 😅

**Comment by jstarry** [comment]
@aeyakovenko I believe this is resolved now that pay to play is opt-in now. Before, each tab would detect new funds and try to start a game at the same time which I think was part of the problem. Feel free to reopen if you see it again!
