### ISSUE TITLE
Transaction signing slows down throughput

### ISSUE THREAD

**Issue by jstarry** [solana-labs/break#311]
#### Problem
Transaction signing is done on the main UI thread and is a bottleneck for sending high TPS

#### Proposed Solution
Send the serialized tx to a web worker for signing

**Comment by oJshua** [comment]
One thing of note, I am creating the transaction in the web worker as well. This may actually be negligible performance wise, but it made some sense to keep the functionality together. We can certainly do just the signing in another iteration if necessary.
