### ISSUE TITLE
Move "Play Again" button away from "Send New Transaction" button

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/break#374]
When mouse clicking laptop/desktop, as soon as the game ends, the "Send Tx" button turns into the "Play Again" button, so if you are just smashing clicks and still have funds, you will automatically start a new game and not see the final stats from your previous play.

Consider a pop up or moving the Play Again button somewhere else on screen so it's not accidentally clicked.

**Comment by jstarry** [comment]
Fixed
