### ISSUE TITLE
Confirmation time calculation is incorrect

### ISSUE THREAD

**Issue by jstarry** [solana-labs/break#8]
#### Problem

This is not a correct way to calculate transaction confirmation time.
```
            const t1 = performance.now();
            const response = await this.connection.sendTransaction(transaction, this.keypair);
            const t2 = performance.now();
```
All this is doing is broadcasting a transaction to the network. Next, the network sends the transaction to the leader node who will then process the transaction and eventually produce a block with the results of this transaction (if it succeeds).

#### Proposed Solution
Make use of https://solana-labs.github.io/solana-web3.js/function/index.html#static-function-sendAndConfirmRecentTransaction or https://solana-labs.github.io/solana-web3.js/class/src/connection.js~Connection.html#instance-method-confirmTransaction to get the correct transaction confirmation time

**Comment by igorburak-zenio** [comment]
This issue is closed. Currently we are using sendAndConfirmRecentTransaction method.
